# Configurações do Banco de Dados H2 (desenvolvimento)
spring.datasource.url=jdbc:h2:mem:labdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
application.security.jwt.secret-key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
# 24 horas em milissegundos
application.security.jwt.expiration=86400000
# 7 dias em milissegundos
application.security.jwt.refresh-token.expiration=604800000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Configurações de Segurança
spring.security.user.name=admin
spring.security.user.password={bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW

# Configuracoes do Servidor
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# Logging
logging.level.br.com.devvinnas=DEBUG
logging.level.org.springframework.security=DEBUG